services:
  rtsptohls:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN:-*}
    expose:
      - "8083"
    volumes:
      - /data/rtsphls/config.json:/app/config.json:ro
