services:
  rtsptohls:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8083"
    volumes:
      - /data/rtsphls/config.json:/app/config.json:ro
